### ISSUE TITLE
Unchecked lastError value: Error: username[0] is undefined

### ISSUE THREAD

**Issue by sanitysama** [mmduser1/iwara_source_downloader#16]
`Unchecked lastError value: Error: username[0] is undefined [background.js:7](moz-extension://f5b61188-f241-4c38-bab1-f1d842403434/background.js)
    <anonymous> moz-extension://f5b61188-f241-4c38-bab1-f1d842403434/background.js:7`

https://ecchi.iwara.tv/videos/8ney1uzbeviqdqmk2

**Comment by mmduser1** [comment]
I will check.

**Comment by mmduser1** [comment]
Perhaps it is no longer necessary due to Iwara's site change.
Please let me know if there are any errors.
