### ISSUE TITLE
Iwara website updated and addon no longer works

### ISSUE THREAD

**Issue by sealclubber** [mmduser1/iwara_source_downloader#17]
Iwara's main website was updated recently which broke this extension. Is there a way we can get an update?

**Comment by mmduser1** [comment]
Thank you for the notice. I will respond to updates on the Iwara website soon.

But that update is not available from the Chrome Web Store.
The Chrome Web Store has determined that IwaraSourceDownloader is a policy violation and will not allow the update.
I plan to write the installation method on GitHub.

**Comment by sealclubber** [comment]
Works like a charm on firefox, haven't tested on chrome. I tested a couple of different vids and the ones that _do_ load work fine. Looks like the site admins have a lot of work ahead of them. 

Anyway thanks for the quick turnaround!
