### ISSUE TITLE
新サイトだと機能していない？

### ISSUE THREAD

**Issue by NaokiSato102** [mmduser1/iwara_source_downloader#21]
ボタンを押しても下記のが出るだけです。  
CocCocなので、素クロームで無いせいかもですが。
![image](https://user-images.githubusercontent.com/27545766/227770375-31ef13e2-f8eb-4fed-81b8-e65221f85cd2.png)

**Comment by mmduser1** [comment]
Chromeウェブストアからインストールしたものでしょうか？
もしそうであればそれは使用できません
[releases](https://github.com/mmduser1/iwara_source_downloader/releases)からzipをダウンロードしてデベロッパーモードでv4.0.0の導入をお願いします

**Comment by NaokiSato102** [comment]
審査の類がまだなせいですか。了解です。

**Comment by mmduser1** [comment]
Chromeウェブストアはポリシー違反としてこのアドオンの更新を拒否したので、
ウェブストア経由での更新は二度とありません
