### ISSUE TITLE
error on chrome

### ISSUE THREAD

**Issue by PAPAYAnpapaya** [mmduser1/iwara_source_downloader#22]
sorry to interrupt, i encounter this error when i install it and it couldn't do the download

(Uncaught (in promise) Error: Could not establish connection. Receiving end does not exist.)
background.js:0 (匿名函式)

**Comment by mmduser1** [comment]
@PAPAYAnpapaya 
・Temporary measures
Please reload page and then click the icon.

This error is related to:
https://github.com/mmduser1/iwara_source_downloader/issues/18
Please wait for it to be fully resolved.
