### ISSUE TITLE
Addon no longer functioning on firefox

### ISSUE THREAD

**Issue by sealclubber** [mmduser1/iwara_source_downloader#25]
Clicking the button gives no response. It was working fine yesterday so it's probably on the iwara end. Is anyone else having this issue?

**Comment by mmduser1** [comment]
This is due to Iwara changing the display format of the number of likes.
Fixed in 4.0.3
https://github.com/mmduser1/iwara_source_downloader/releases/tag/v4.0.3

**Comment by sealclubber** [comment]
Thanks for the quick response, it works now. You are the best :)
