### ISSUE TITLE
Not working in Chrome

### ISSUE THREAD

**Issue by Kliv77788** [mmduser1/iwara_source_downloader#30]
I can't even open it.

Context:
background.js

Stack Trace:
background.js:0 (anonymous function)

![image](https://github.com/mmduser1/iwara_source_downloader/assets/144236024/a3430963-1a19-46fb-9b12-6056abf6edf5)

**Comment by mmduser1** [comment]
@Kliv77788 
Please tell me which version you are using.

As a temporary workaround, please refresh the page and try again.

**Comment by Kliv77788** [comment]
> @Kliv77788 Please tell me which version you are using.
> 
> As a temporary workaround, please refresh the page and try again.

Sorry, I thought your extension had an interface. I checked on the video page. The video is downloading. Thank you.
