### ISSUE TITLE
is it possible to add function of automically click like button

### ISSUE THREAD

**Issue by zhailingzy** [mmduser1/iwara_source_downloader#5]
ad I downloaded the video I think it is polite to click like button.

**Comment by mmduser1** [comment]
I'll work on it.

**Comment by mmduser1** [comment]
https://github.com/mmduser1/iwara_source_downloader/commit/68e00098fa02e76fef5fae68e653031ed6dd000d

Click Like button at the same time as downloading.
Please let me know if you have any problems.
