### ISSUE TITLE
ダウンロード時のファイル名が無効

### ISSUE THREAD

**Issue by ForteScarlet** [mmduser1/iwara_source_downloader#7]
今日使っていて気づいたのですが、ダウンロード時にファイル名が設定されたテンプレートではなく、サイトのデフォルト名になっていました。

**Comment by ForteScarlet** [comment]
ブラウザはchrome

**Comment by mmduser1** [comment]
@ForteScarlet 
返信が遅れまして申し訳ありません。ご報告ありがとうございます。

> ダウンロード時にファイル名が設定されたテンプレートではなく、サイトのデフォルト名になっていました。

他のダウンロード系アドオンと競合するとこの種の問題が起こりがちです。悪いことにこれはブラウザの仕様のため、アドオン側で対応するのが現状困難となっていて修正も厳しい状況です。

取り急ぎダウンロードに関係するアドオンを一旦すべて停止して、ファイル名が正常に取得できるか試してみてください。

**Comment by ForteScarlet** [comment]
お返事を書いていただきありがとうございました。
少し前に再挑戦したところ、勝手に元に戻ってしまいました。
以前この問題が発生したときは、iwaraの改修・アップグレード時だったようなので、一時的なバグだったのかもしれません。
問題は修正されました、ありがとうございました
(Translated via deepL)
